Repository eventespresso/eea-importer, pull requests merged in 2019-05, with the labels that each got.

#33 Added help tabs and nonces
  src/application/services/import/ImportManager.php
  src/application/services/import/ImportTypeUiManagerInterface.php
  src/domain/services/import/csv/attendees/forms/form_handlers/ChooseEvent.php
  src/domain/services/import/csv/attendees/forms/form_handlers/ChooseTicket.php
  src/domain/services/import/csv/attendees/forms/form_handlers/ImportCsvAttendeesStep.php
  src/domain/services/import/csv/attendees/forms/form_handlers/MapCsvColumns.php
  src/domain/services/import/csv/attendees/forms/form_handlers/StepsManager.php
  src/domain/services/import/csv/attendees/forms/form_handlers/UploadCSV.php
  src/domain/services/import/csv/attendees/forms/forms/MapCsvColumnsForm.php
  src/domain/services/import/csv/attendees/forms/forms/UploadCSVForm.php
  src/domain/services/import/csv/attendees/templates/ee_attendee_importer_mapping_instructions.template.php
  src/ui/admin/attendee_importer/Attendee_Importer_Admin_Page.core.php
  src/ui/admin/attendee_importer/help_tabs/attendee_importer_import_choose-event.help_tab.php
  src/ui/admin/attendee_importer/help_tabs/attendee_importer_import_choose-ticket.help_tab.php
  src/ui/admin/attendee_importer/help_tabs/attendee_importer_import_map.help_tab.php
  src/ui/admin/attendee_importer/help_tabs/attendee_importer_import_overview.help_tab.php
  src/ui/admin/attendee_importer/help_tabs/attendee_importer_import_upload.help_tab.php
Labels: category:admin-page-ui-&-ux, status:needs-documentation, type:enhancement 🎉

#35 Update strings to use new helper method for branding
  eea-attendee-importer.php
  src/domain/services/import/csv/attendees/forms/forms/MapCsvColumnsSubform.php
  src/domain/services/import/csv/attendees/templates/ee_attendee_importer_mapping_instructions.template.php
  src/ui/admin/attendee_importer/help_tabs/attendee_importer_import_map.help_tab.php
  src/ui/admin/attendee_importer/help_tabs/attendee_importer_import_overview.help_tab.php
Labels: status:in-progress

#37 Fet/caps
  src/EE_Attendee_Importer.class.php
  src/application/services/import/ImportManager.php
  src/application/services/import/ImportTypeManagerInterface.php
  src/domain/services/commands/ImportBaseCommand.php
  src/domain/services/import/csv/attendees/templates/ee_attendee_importer_mapping_instructions.template.php
  src/domain/services/import/managers/ImportCsvAttendeesManager.php
  src/ui/admin/attendee_importer/Attendee_Importer_Admin_Page.core.php
  src/ui/admin/attendee_importer/Attendee_Importer_Admin_Page_Init.core.php
  src/ui/admin/attendee_importer/espresso_events_Attendee_Importer_Hooks.class.php
  src/ui/admin/attendee_importer/help_tabs/attendee_importer_import_map.help_tab.php
  src/ui/admin/attendee_importer/help_tabs/attendee_importer_import_overview.help_tab.php
Labels: category:models-and-data-infrastructure, category:security, status:needs-testing, type:enhancement 🎉

#41 Rename files so they load when expected
  src/domain/services/import/csv/attendees/templates/ee_importer_mapping_instructions.template.php
  src/domain/services/import/csv/attendees/templates/importer_verify_info.template.php
Labels: status:merge, type:bug 🐞

#40 Don't autofill event or ticket
  src/application/services/import/ImportManager.php
  src/domain/services/import/csv/attendees/forms/form_handlers/ChooseEvent.php
  src/domain/services/import/csv/attendees/forms/form_handlers/ChooseTicket.php
  src/domain/services/import/csv/attendees/templates/importer_verify_info.template.php
  src/ui/admin/importer/Importer_Admin_Page.core.php
Labels: status:needs-testing, type:bug 🐞

#43 Fix payments not applying to transactions and registrations
  src/domain/services/commands/ImportCommandHandler.php
  src/domain/services/commands/ImportRegistrationCommandHandler.php
Labels: category:reports-exporting-importing, status:needs-testing, type:bug 🐞
